<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { api } from '../api';
type Room={roomNumber:number;title:string;cover?:string;streamStatus:string;viewerCount:number;owner:{nickname:string;avatar?:string};category?:{name:string;slug:string}}; type Category={id:number;name:string;slug:string};
const route=useRoute(),router=useRouter(),rooms=ref<Room[]>([]),categories=ref<Category[]>([]),loading=ref(true),search=ref(String(route.query.q??'')),error=ref('');
async function load(){loading.value=true;error.value='';try{const params=new URLSearchParams({status:'LIVE'});const slug=String(route.params.slug??'');if(slug)params.set('category',slug);if(route.path==='/search'&&route.query.q)params.set('search',String(route.query.q));rooms.value=(await api<{data:Room[]}>(`/api/rooms?${params}`)).data;categories.value=(await api<{data:Category[]}>('/api/categories')).data}catch(e){error.value=(e as {message:string}).message}finally{loading.value=false}}
function doSearch(){router.push({path:'/search',query:{q:search.value}})} onMounted(load);watch(()=>route.fullPath,load);
</script>
<template><section class="hero"><div><h1>此刻，正在发生</h1><p>发现真实、即时的内容，或创建自己的直播间，通过 OBS 即刻开播。</p><div class="search"><input v-model="search" class="input" placeholder="搜索直播标题、主播" @keyup.enter="doSearch"><button class="button primary-button" @click="doSearch">搜索</button></div></div><button class="button" @click="$router.push('/me/room')">我要开播</button></section>
<div class="section-head"><h2>{{route.path==='/search'?`“${route.query.q??''}” 的结果`:'正在直播'}}</h2><div><router-link v-for="c in categories" :key="c.id" :to="`/categories/${c.slug}`" style="margin-left:16px" class="muted">{{c.name}}</router-link></div></div>
<p v-if="error" class="error">{{error}}</p><p v-else-if="loading" class="muted">正在加载直播间…</p><div v-else-if="rooms.length" class="grid"><router-link v-for="room in rooms" :key="room.roomNumber" :to="`/room/${room.roomNumber}`" class="room-card"><div class="cover"><img v-if="room.cover" :src="room.cover" :alt="room.title"><span class="live-badge">直播中</span><span class="viewer">{{room.viewerCount}} 人</span></div><div class="card-body"><div class="card-title">{{room.title}}</div><div class="card-meta"><span>{{room.owner.nickname}}</span><span>{{room.category?.name??'未分类'}}</span></div></div></router-link></div><div v-else class="panel muted">暂时没有符合条件的直播，稍后再来看看。</div></template>
