<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { api } from '../api'; import { useAppStore } from '../stores/app';
type Room={roomNumber:number;title:string;description?:string;announcement?:string;cover?:string;visibility:'PUBLIC'|'PRIVATE';showViewerCount:boolean;recordReplay?:boolean;streamStatus:string;sessions:{id:string;startedAt:string;endedAt?:string;durationSeconds?:number;peakViewers:number;recordingUrl?:string}[]};
const store=useAppStore(),rooms=ref<Room[]>([]),error=ref(''),saved=ref(''),key=ref<{server:string;streamKey:string;playback:string}|null>(null),showKey=ref(false); const current=computed(()=>rooms.value[0]); const form=reactive({title:'我的直播间',description:'',announcement:'',cover:'',visibility:'PUBLIC',showViewerCount:true,recordReplay:true});
const coverInput=ref<HTMLInputElement>(),applyContent=ref(''),applyStatus=ref<{status:string;createdAt?:string}|null>(null);
async function load(){try{rooms.value=(await api<{data:Room[]}>('/api/users/me/rooms')).data;if(current.value)Object.assign(form,current.value)}catch(e){error.value=(e as {message:string}).message}}
async function loadApply(){if(!store.user||store.user.canStream)return;try{applyStatus.value=(await api<{data:{status:string}|null}>('/api/notices/stream-permission')).data}catch(e){error.value=(e as {message:string}).message}}
async function applyStream(){try{await api('/api/notices/stream-permission',{method:'POST',body:JSON.stringify({content:applyContent.value})});saved.value='申请已提交，请等待管理员审核';await loadApply()}catch(e){error.value=(e as {message:string}).message}}
async function save(){try{if(current.value)await api(`/api/rooms/${current.value.roomNumber}`,{method:'PATCH',body:JSON.stringify(form)});else await api('/api/rooms',{method:'POST',body:JSON.stringify(form)});saved.value='已保存';await load()}catch(e){error.value=(e as {message:string}).message}}
async function uploadCover(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{const fd=new FormData();fd.append('file',file);const res=await api<{data:{url:string}}>('/api/uploads/images',{method:'POST',body:fd});form.cover=res.data.url;saved.value='封面已上传，点击"保存直播设置"生效'}catch(err){error.value=(err as {message:string}).message}}
async function loadKey(){if(!current.value)return;key.value=(await api<{data:{server:string;streamKey:string;playback:string}}>(`/api/rooms/${current.value.roomNumber}/stream`)).data}
async function rotate(){if(!current.value||!confirm('重新生成后，旧推流密钥将立即失效，OBS 中需要重新配置。确定继续？'))return;const r=await api<{data:{streamKey:string}}>(`/api/rooms/${current.value.roomNumber}/stream/rotate`,{method:'POST'});if(key.value)key.value.streamKey=r.data.streamKey;showKey.value=true}
async function copy(v:string){await navigator.clipboard.writeText(v);saved.value='已复制'} onMounted(async()=>{if(!store.user)await store.bootstrap();await loadApply();await load();if(current.value)await loadKey()});
</script>
<template><div class="sidebar-layout"><aside class="panel sidebar"><router-link to="/me/room">直播设置</router-link><router-link to="/me/stream">推流设置</router-link><router-link to="/me/sessions">直播记录</router-link></aside><section><div v-if="store.user&&!store.user.canStream" class="panel"><h2>开播权限</h2><template v-if="applyStatus?.status==='PENDING'"><p class="success">申请已提交，等待管理员审核中</p></template><template v-else><p class="muted">您当前没有开播权限。向管理员提交申请，批准后即可创建直播间并推流。</p><textarea v-model="applyContent" class="input" rows="3" maxlength="1000" placeholder="申请理由（可选）"></textarea><button type="button" class="button primary-button" @click="applyStream">提交开播申请</button><p v-if="applyStatus?.status==='REJECTED'" class="error">上次申请未通过，可重新提交</p></template></div><div class="panel" style="margin-top:20px"><h1>我的直播间</h1><p v-if="current" class="muted">房间号 {{current.roomNumber}} · {{current.streamStatus}}</p><form class="form" @submit.prevent="save"><label>直播标题<input v-model="form.title" class="input" required maxlength="120"></label><label>封面<div class="search"><input v-model="form.cover" class="input" placeholder="图片 URL，或点击上传（JPG / PNG / WebP，推荐 16:9）"><button type="button" class="button" @click="coverInput?.click()">上传</button></div><img v-if="form.cover" class="cover-preview" :src="form.cover" alt="封面预览"><input ref="coverInput" type="file" accept="image/jpeg,image/png,image/webp" hidden @change="uploadCover"></label><label>直播简介<textarea v-model="form.description" class="input" rows="3"></textarea></label><label>直播公告<textarea v-model="form.announcement" class="input" rows="3"></textarea></label><label>可见性<select v-model="form.visibility" class="input"><option value="PUBLIC">公开</option><option value="PRIVATE">私有（仅可通过房间号进入）</option></select></label><label><span><input v-model="form.showViewerCount" type="checkbox"> 显示在线人数</span></label><label><span><input v-model="form.recordReplay" type="checkbox"> 生成直播回放</span><small>在开播前设置，对下一场直播生效。关闭后本场直播结束不保留回放。</small></label><p v-if="error" class="error">{{error}}</p><p v-if="saved" class="success">{{saved}}</p><button class="button primary-button">{{current?'保存直播设置':'创建直播间'}}</button></form></div>
<div v-if="current&&key" class="panel" style="margin-top:20px"><h2>OBS 推流设置</h2><p class="muted">推流真正接入 SRS 后，直播状态才会自动变为 LIVE。</p><div class="form"><label>RTMP Server<div class="search"><input :value="key.server" readonly class="input"><button type="button" class="button" @click="copy(key.server)">复制</button></div></label><label>Stream Key<input :value="showKey?key.streamKey:'••••••••••••••••••••'" readonly class="input"></label><div><button type="button" class="button" @click="showKey=!showKey">{{showKey?'隐藏':'显示'}}</button> <button type="button" class="button" @click="copy(key.streamKey)">复制</button> <button type="button" class="button" @click="rotate">重新生成</button></div></div></div>
<div v-if="current?.sessions?.length" class="panel" style="margin-top:20px"><h2>直播记录</h2><table class="data-table"><thead><tr><th>开始</th><th>结束</th><th>时长</th><th>峰值在线</th><th>回放</th></tr></thead><tbody><tr v-for="s in current.sessions" :key="s.id"><td>{{new Date(s.startedAt).toLocaleString()}}</td><td>{{s.endedAt?new Date(s.endedAt).toLocaleString():'直播中'}}</td><td>{{s.durationSeconds??'-'}} 秒</td><td>{{s.peakViewers}}</td><td><router-link v-if="s.recordingUrl" class="table-link" :to="`/room/${current.roomNumber}`">观看</router-link><span v-else class="muted">未生成</span></td></tr></tbody></table></div></section></div></template>
