<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { api } from '../api'; import { useAppStore } from '../stores/app';
const store=useAppStore(),error=ref(''),message=ref('');const profile=reactive({nickname:'',bio:'',avatar:''}),password=reactive({currentPassword:'',newPassword:''});
const avatarInput=ref<HTMLInputElement>();
onMounted(async()=>{if(!store.user)await store.bootstrap();if(store.user)Object.assign(profile,{nickname:store.user.nickname,avatar:store.user.avatar??''})});
async function save(){try{await api('/api/users/me',{method:'PATCH',body:JSON.stringify(profile)});message.value='资料已更新';await store.bootstrap()}catch(e){error.value=(e as {message:string}).message}}
async function uploadAvatar(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{const fd=new FormData();fd.append('file',file);const res=await api<{data:{url:string}}>('/api/uploads/images',{method:'POST',body:fd});profile.avatar=res.data.url;message.value='头像已上传，点击"保存资料"生效'}catch(err){error.value=(err as {message:string}).message}}
async function change(){try{await api('/api/auth/change-password',{method:'POST',body:JSON.stringify(password)});message.value='密码已修改，请重新登录'}catch(e){error.value=(e as {message:string}).message}}
</script>
<template><div class="sidebar-layout"><aside class="panel sidebar"><router-link to="/me">账号信息</router-link><router-link to="/me/security">安全设置</router-link><router-link to="/me/room">我的直播间</router-link></aside><section><div class="panel"><h1>个人中心</h1><form class="form" @submit.prevent="save"><label>昵称<input v-model="profile.nickname" class="input"></label><label>头像<div class="search"><input v-model="profile.avatar" class="input" placeholder="图片 URL，或点击上传"><button type="button" class="button" @click="avatarInput?.click()">上传</button></div><img v-if="profile.avatar" class="avatar-preview" :src="profile.avatar" alt="头像预览"><input ref="avatarInput" type="file" accept="image/jpeg,image/png,image/webp" hidden @change="uploadAvatar"></label><label>个人简介<textarea v-model="profile.bio" class="input"></textarea></label><button class="button primary-button">保存资料</button></form></div><div class="panel" style="margin-top:20px"><h2>修改密码</h2><form class="form" @submit.prevent="change"><label>当前密码<input v-model="password.currentPassword" type="password" class="input"></label><label>新密码<input v-model="password.newPassword" type="password" class="input"></label><button class="button">修改密码</button></form><p v-if="error" class="error">{{error}}</p><p v-if="message" class="success">{{message}}</p></div></section></div></template>
